server:
  port: 8083

spring:
  application:
    name: analytics-service

  datasource:
    url: jdbc:postgresql://localhost:5432/webnovel_compass
    username: atrafelis
    password: atrafelis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info