version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15-alpine
    container_name: webnovel-compass-db
    environment:
      POSTGRES_DB: webnovel_compass
      POSTGRES_USER: webnovel_user
      POSTGRES_PASSWORD: webnovel_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../database/init:/docker-entrypoint-initdb.d
    networks:
      - webnovel-network
    restart: unless-stopped

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: webnovel-compass-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - webnovel-network
    restart: unless-stopped

  # PgAdmin (PostgreSQL 관리 도구)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: webnovel-compass-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@webnovelcompass.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - webnovel-network
    restart: unless-stopped
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  webnovel-network:
    driver: bridge
